### PR TITLE
Apple old website clone project is complete and now submitting for a code review.

### PR DESCRIPTION
**Pull request by aulbytj**

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status: Require Changes🛑
Hi @aulbytj🙋‍♂️,
Good first attempt on this one🙂. Here are a few changes we have to make to get this project 💪.
* [x] Let us enable linter checks on this repo. Visit [stickler-ci.com](stickler-ci.com).
* [x] Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store) 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [x] The navbar does not look good let us fix
This your page navbar👇
Screenshot from 2020-01-28 16-11-56
compare it with the original
* [x] Let us get rid of the horizontal scroll on the page
This your page navbar👇
Screenshot from 2020-01-28 16-12-25
## That is it kindly make these changes and submit the project for review🙂
#### Happy coding💻
#### Addo Forison

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status : Require changes 🔴

Hi @aulbytj, :slightly_smiling_face:  great job making the changes requested by previous reviewer. There is still horizontal scroll. 
lasty
Here is a quick fix : 
- Kindly change the width of the class ``` .ads ``` to ``` 100%```. So that it fits on all screen sizes.

Kindly make this change and submit another code review :+1: 
Happy coding:computer: 

[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

**Comment by Anna-Myzukina** [comment]
## Hi @aulbytj !


* I noticed that you've made some changes according to the previous review, great job.
However, for this project to be approved, you need to add a descriptive readme file.

#### General

* The project has a descriptive README.md
screen

I hope this article can help you [Professional Github repository](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
* Kindly recommended in your next projects
screen


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*


*Happy coding 😄*

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
